resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: master
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/FTP
    - release/FTP/*
    - support/FTP/*
  paths:
    include:
    - '/Activities/FTP/*'
    - '/Activities/Activities.FTP.sln'

pr:
  branches:
    include:
    - develop
    - masters/FTP
    - release/FTP/*
    - support/FTP/*
  paths:
    include:
    - '/Activities/FTP/*'
    - '/Activities/Activities.FTP.sln'

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'FTP'
      solutionPath: '$(Build.SourcesDirectory)/Activities/Activities.FTP.sln'
      buildPoolName: 'activities-build'
      testPoolName: 'activities-build'
      sdkBuild: true
      enableCDStages: false
