resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: master
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Java
    - release/Java/*
    - support/Java/*
  paths:
    include:
    - '/Activities/Java/*'
    - '/Activities/Activities.Java.sln'

pr:
  branches:
    include:
    - develop
    - masters/Java
    - release/Java/*
    - support/Java/*
  paths:
    include:
    - '/Activities/Java/*'
    - '/Activities/Activities.Java.sln'

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'Java'
      solutionPath: '$(Build.SourcesDirectory)/Activities/Activities.Java.sln'
      buildPoolName: 'activities-build'
      testPoolName: 'activities-build'
      sdkBuild: true
      enableCDStages: false
