parameters:
  BuildProject: ""
  BuildConfiguration: "Release"
  BuildPlatform: "AnyCPU"
  NuGetVersionSpec: "4.3.0"
  NuGetConfigPath: "$(Build.SourcesDirectory)/Activities/.nuget/NuGet.Config"
  Dependencies: []
  restoreDependencies: []
  rootPath: $(Build.SourcesDirectory)
  packagesDirectory: ""
  versionNumber: ""
  versionSuffix: ""

steps:
 - task: DotNetCoreCLI@2
   displayName: "dotnet restore Nuget packages"
   inputs:
     command:            "restore"
     feedsToUse:         "config"
     includeNuGetOrg:    true
     nugetConfigPath:    ${{ parameters.NuGetConfigPath }}
     packDirectory:      ${{ parameters.packagesDirectory }}
     projects:           |
        Activities/Java/**/*.csproj
        Activities/FTP/**/*.csproj

 - task: DotNetCoreCLI@2
   displayName: "dotnet Build Solution"
   inputs:
     command:            "build"
     arguments:          "--configuration ${{ parameters.BuildConfiguration }} -p:version=$(versionNumber)-$(versionSuffix)"
     projects:           |
        Activities/FTP/**/*.csproj
