parameters:
  BuildProject: ""
  BuildConfiguration: "Release"
  rootPath: $(Build.SourcesDirectory)

steps:
- task: PowerShell@1
  displayName: "Set 'PackagesToPack' variable"
  inputs:
    scriptType: "inlineScript"
    inlineScript: |
      Write-Output $ENV:BUILD_SOURCESDIRECTORY
      Write-Output $files
      $files = Get-ChildItem "${{ parameters.rootPath }}*Packaging.csproj" -Recurse 
      Write-Output $files
      #$pattern = '' 
      #ForEach($file in $files) { $pattern+="**\$file;" } 
      #Write-Output "Pattern " + $pattern
      Write-Host "##vso[task.setvariable variable=PackagesToPack;]$files" 

- task: DotNetCoreCLI@2
  displayName: "Create Nuget packages ${{ parameters.BuildProject }}"
  inputs: 
    command: 'pack'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    packagesToPack: "$(PackagesToPack)"
    versioningScheme: "byEnvVar"
    includeSymbols: "true"
    configurationToPack: ${{ parameters.BuildConfiguration }}
    versionEnvVar: "BUILD_BUILDNUMBER"

- task: PublishBuildArtifacts@1
  displayName: "Publish symbols"
  inputs:
    PathtoPublish:  '$(Build.ArtifactStagingDirectory)'
    ArtifactName:   'Setup'
    ArtifactType:   'Container'
    