resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: feature/activities_templates
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Python
    - release/Python/*
    - support/Python/*
  paths:
    include:
    - Activities/Python/*
    - Activities/Activities.Python.sln

pr:
  branches:
    include:
    - develop
    - masters/Python
    - release/Python/*
    - support/Python/*
  paths:
    include:
    - Activities/Python/*
    - Activities/Activities.Python.sln

variables:
  - template: ..\.pipelines\variables\variables.yml

extends:
  template: Activities/stage.start.yml@common
  parameters:
    projectName: 'Python'
    solutionPath: '$(SolutionsPath)/Activities.Python.sln'
    buildPoolName: 'activities-build'
    testPoolName: 'activities-build'
    sdkBuild: false
    enableCDStages: false