resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: master
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Python
    - release/Python/*
    - support/Python/*
  paths:
    include:
    - '/Activities/Python/*'
    - '/Activities/Activities.Python.sln'

pr:
  branches:
    include:
    - develop
    - masters/Python
    - release/Python/*
    - support/Python/*
  paths:
    include:
    - '/Activities/Python/*'
    - '/Activities/Activities.Python.sln'

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'Python'
      solutionPath: '$(Build.SourcesDirectory)/Activities/Activities.Python.sln'
      buildPoolName: 'activities-build'
      testPoolName: 'activities-build'
      sdkBuild: false
      enableCDStages: false
